name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: "stable"

      - name: Install dependencies
        working-directory: ./flappy_bird_flutter
        run: flutter pub get

      # - name: Run tests
      #   working-directory: ./flappy_bird_flutter
      #   run: flutter test

      - name: Build web
        working-directory: ./flappy_bird_flutter
        run: flutter build web --base-href "/flappy-bird-flutter/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flappy_bird_flutter/build/web
